### ISSUE TITLE
Support Merging

### ISSUE THREAD

**Issue by KyleJamesWalker** [KyleJamesWalker/yamlsettings#7]
Example settings file:

``` yaml
development: &development_base
  a: A
  b: B
  c: C
development_alternate:
  <<: *development_base
  c: X
```

Right now the generates the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/usr/local/lib/python2.7/dist-packages/yamlsettings/__init__.py", line 162, in __init__
    self.settings = load(override_settings)
  File "/usr/local/lib/python2.7/dist-packages/yamlsettings/__init__.py", line 47, in load
    yaml_dict = yamldict.load(open(filepath))
  File "/usr/local/lib/python2.7/dist-packages/yamlsettings/yamldict.py", line 171, in load
    return loader.get_single_data()
  File "/usr/local/lib/python2.7/dist-packages/yaml/constructor.py", line 39, in get_single_data
    return self.construct_document(node)
  File "/usr/local/lib/python2.7/dist-packages/yaml/constructor.py", line 48, in construct_document
    for dummy in generator:
  File "/usr/local/lib/python2.7/dist-packages/yamlsettings/yamldict.py", line 134, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/usr/local/lib/python2.7/dist-packages/yamlsettings/yamldict.py", line 149, in construct_mapping
    key = self.construct_object(key_node, deep=deep)
  File "/usr/local/lib/python2.7/dist-packages/yaml/constructor.py", line 88, in construct_object
    data = constructor(self, node)
  File "/usr/local/lib/python2.7/dist-packages/yaml/constructor.py", line 414, in construct_undefined
    node.start_mark)
yaml.constructor.ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:merge'
```

**Comment by gullpong** [comment]
addressed in
15e38e5787ab972dc655768f437382ceaddc3da8

**Comment by KyleJamesWalker** [comment]
Thanks!!!
